version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - MONGO_URI=mongodb+srv://robert:m8DQGRrye175THlg@cluster0.joirnmx.mongodb.net/

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=robert
      - MONGO_INITDB_ROOT_PASSWORD=m8DQGRrye175THlg
